from typing import Dict, Any
from kfp import dsl
from kfp.dsl import Input, Output, Dataset, Model, Metrics

# Docker image configuration
PROPHET = "europe-west9-docker.pkg.dev/forecast-sales-poc/forecast-sales-images/prophet:latest"

@dsl.component(base_image=PROPHET)
def evaluate_prophet_model(
    model_input: dsl.Input[Model],
    eval_data: dsl.Input[Dataset],
    metrics: dsl.Output[Metrics],
    infra: Dict[str, Any],
    job_params: Dict[str, Any],
) -> bool:
    """
    Evaluates a trained Prophet candidate model against business thresholds using a holdout dataset.

    This component acts as the first Validation Gate. It loads the candidate model and tests
    it against the most recent blind data (e.g., the last 30 days). 
    It computes a set of forecasting metrics, treating WAPE as the primary indicator of
    logistical accuracy. The model is approved to advance to the Champion vs. 
    Challenger evaluation phase ONLY if its performance satisfies all the maximum error 
    thresholds. Passing this gate means the candidate is viable, but it must still defeat 
    the current production model before triggering a Refit. MASE is calculated as an 
    out-of-sample approximation for observability.

    Args:
        model_input (dsl.Input[Model]): 
            The physical artifact containing the serialized Prophet model.
        eval_data (dsl.Input[Dataset]): 
            The holdout validation dataset (validation gate data) in CSV format.
        metrics (dsl.Output[Metrics]): 
            The KFP artifact where validation performance metrics are logged.
        infra (Dict[str, Any]): 
            Global infrastructure configuration (project_id, location).
        job_params (Dict[str, Any]): 
            Evaluation parameters and strict thresholds.
            - max_allowed_wape (float, optional): Maximum acceptable WAPE.
            - max_allowed_mape (float, optional): Maximum acceptable MAPE.
            - max_allowed_mae (float, optional): Maximum acceptable MAE.
            - max_allowed_rmse (float, optional): Maximum acceptable RMSE.
            - max_allowed_abs_bias (float, optional): Maximum acceptable absolute bias.
            - mase_seasonality_period (int): Periodicity for MASE baseline.

    Returns:
        bool: True if the model passes all provided thresholds, False otherwise.
    """

    import os
    import structlog
    import pandas as pd
    import numpy as np
    from prophet.serialize import model_from_json
    from sklearn.metrics import (
        mean_absolute_percentage_error,
        mean_absolute_error,
        mean_squared_error
    )
    from common.core.logger import get_logger
    from common.prophet.helper import compute_forecast_metrics

    # Initialize the application structured logger
    logger = get_logger("evaluation-threshold-task")

    try:

        # Unpack infrastructure and job configuration parameters into local variables
        project_id = infra["project_id"]
        location = infra["location"]
        max_allowed_mape = job_params["max_allowed_mape"]
        max_allowed_wape = job_params["max_allowed_wape"]
        max_allowed_mae = job_params["max_allowed_mae"]
        max_allowed_rmse = job_params["max_allowed_rmse"]
        max_allowed_abs_bias = job_params["max_allowed_abs_bias"]

        # define seasonality period for MASE baseline (if week -> 7; otherwise no, 1)
        seasonality_period = int(job_params.get("mase_seasonality_period", 1))

        # Bind context variables. All subsequent logs will include these fields.
        # This is for filtering logs in GCP Cloud Logging.
        structlog.contextvars.bind_contextvars(
            project_id=project_id,
        )    

        logger.info("Starting model evaluation.", 
                    maximum_allowed_threshold_MAPE=max_allowed_mape,
                    max_allowed_wape=max_allowed_wape,
                    max_allowed_mae=max_allowed_mae,
                    max_allowed_rmse=max_allowed_rmse,
                    max_allowed_abs_bias=max_allowed_abs_bias,
                    mase_seasonality_period=seasonality_period
        )

        # Load the newly trained model from the folder generated by KFP
        model_path = os.path.join(model_input.path, "model.json")
        with open(model_path, 'r') as fin:
            m = model_from_json(fin.read())

        # Load the evaluation data (Test/Holdout Dataset)
        df_eval = pd.read_csv(eval_data.path)

        if "ds" not in df_eval.columns or "y" not in df_eval.columns:
            logger.error("Expected columns 'ds' and 'y' not found.", found_columns=list(df_eval.columns))
            raise ValueError(f"Expected columns 'ds' and 'y' not found. Found columns: {list(df_eval.columns)}")

        df_eval = df_eval.sort_values(by="ds").reset_index(drop=True)  
        
        # Realizar la predicción sobre las fechas de evaluación
        forecast = m.predict(df_eval[["ds"]])
        y_true = df_eval["y"]
        y_pred = forecast["yhat"]

        m_dict = compute_forecast_metrics(
            y_true=y_true,
            y_pred=y_pred,
            seasonality_period=seasonality_period
        )

        logger.info(
            "Performance new model (validation/holdout)",
            val_wape=f"{m_dict['wape']:.6f}",
            val_mape=f"{m_dict['mape']:.6f}",
            val_mae=f"{m_dict['mae']:.6f}",
            val_rmse=f"{m_dict['rmse']:.6f}",
            val_me_bias=f"{m_dict['me_bias']:.6f}",
            val_smape=f"{m_dict['smape']:.6f}",
            val_mase=f"{m_dict['mase']:.6f}" if np.isfinite(m_dict["mase"]) else "nan",
        )

        metrics.log_metric("val_wape", m_dict["wape"])
        metrics.log_metric("val_mape", m_dict["mape"])
        metrics.log_metric("val_mae", m_dict["mae"])
        metrics.log_metric("val_rmse", m_dict["rmse"])
        metrics.log_metric("val_me_bias", m_dict["me_bias"])
        metrics.log_metric("val_smape", m_dict["smape"])
        metrics.log_metric("val_mase", m_dict["mase"])

        is_approved = True
        
        if max_allowed_wape is not None:
            is_approved = is_approved and (m_dict["wape"] <= float(max_allowed_wape))
        if max_allowed_mape is not None:
            is_approved = is_approved and (m_dict["mape"] <= float(max_allowed_mape))
        if max_allowed_mae is not None:
            is_approved = is_approved and (m_dict["mae"] <= float(max_allowed_mae))
        if max_allowed_rmse is not None:
            is_approved = is_approved and (m_dict["rmse"] <= float(max_allowed_rmse))
        if max_allowed_abs_bias is not None:
            is_approved = is_approved and (abs(m_dict["me_bias"]) <= float(max_allowed_abs_bias))

        if is_approved:
            logger.info("Model APPROVED! It passes threshold(s). It will be submitted for registration.")
        else:
            logger.warning("Model REJECTED. It fails one or more threshold(s).")

        metrics.log_metric("gate_passed", 1.0 if is_approved else 0.0)

        return is_approved

    except Exception as e:
        logger.error("Failure during model evaluation", error=str(e))
        raise RuntimeError(f"Failure during model evaluation: {e}") from e        