import numpy as np
import pandas as pd
from typing import Dict, Tuple, List, Optional, Any
from sklearn.metrics import (
    mean_absolute_percentage_error,
    mean_absolute_error,
    mean_squared_error
)
from google.cloud import storage

def compute_forecast_metrics(
    y_true: pd.Series,
    y_pred: pd.Series,
    seasonality_period: int = 1
) -> Dict[str, float]:
    """
    Computes a comprehensive set of time series forecasting performance metrics.

    Note on MASE: In this implementation, MASE is scaled using the evaluation 
    dataset (y_true) rather than the historical training dataset. While standard 
    MASE formulation requires the training set to compute the naive baseline error, 
    this approach provides an efficient out-of-sample approximation when training 
    data is omitted from the function arguments.

    Args:
        y_true (pd.Series): 
            The actual, observed values (ground truth) for the evaluation period.
        y_pred (pd.Series): 
            The predicted values generated by the forecasting model.
        seasonality_period (int, optional): 
            The seasonal frequency of the data (e.g., 7 for weekly seasonality on 
            daily data). Used specifically for the naive baseline in MASE. Defaults to 1.

    Returns:
        Dict[str, float]: A dictionary containing the following calculated metrics:
            - mape: Mean Absolute Percentage Error.
            - mae: Mean Absolute Error.
            - rmse: Root Mean Squared Error.
            - me_bias: Mean Error (indicates systematic over/under forecasting bias).
            - wape: Weighted Absolute Percentage Error (primary metric for volume).
            - smape: Symmetric Mean Absolute Percentage Error.
            - mase: Mean Absolute Scaled Error (approximated on evaluation set).
    """
    y_true = pd.Series(y_true).astype(float).reset_index(drop=True)
    y_pred = pd.Series(y_pred).astype(float).reset_index(drop=True)

    eps = 1e-8

    mape = float(mean_absolute_percentage_error(y_true, y_pred))
    mae = float(mean_absolute_error(y_true, y_pred))
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    me_bias = float((y_pred - y_true).mean())

    wape = float(np.sum(np.abs(y_true - y_pred)) / (np.sum(np.abs(y_true)) + eps))
    smape = float(np.mean(2.0 * np.abs(y_true - y_pred) / (np.abs(y_true) + np.abs(y_pred) + eps)))

    # MASE approximation scaled on evaluation set
    s = max(1, int(seasonality_period))
    if len(y_true) > s:
        naive_err = np.abs(y_true[s:].values - y_true[:-s].values)
        denom = float(np.mean(naive_err))
        mase = float(mae / (denom + eps)) if denom > 0 else float("nan")
    else:
        mase = float("nan")

    return {
        "mape": mape,
        "mae": mae,
        "rmse": rmse,
        "me_bias": me_bias,
        "wape": wape,
        "smape": smape,
        "mase": mase,
    }

# ---------- Cloud Storage Helper functions ----------
def parse_gcs_uri(uri: str):
    if not uri.startswith("gs://"):
        raise ValueError(f"Unsupported artifact_uri (expected gs://...): {uri}")
    no_scheme = uri.replace("gs://", "", 1)
    parts = no_scheme.split("/", 1)
    bucket = parts[0]
    prefix = parts[1] if len(parts) > 1 else ""
    return bucket, prefix

def download_text_from_gcs(gcs_uri: str, filename: str) -> str:
    client = storage.Client()
    bucket_name, prefix = parse_gcs_uri(gcs_uri)
    blob_path = f"{prefix.rstrip('/')}/{filename}".lstrip("/")
    blob = client.bucket(bucket_name).blob(blob_path)
    return blob.download_as_text()

def pick_latest_model(models):
    # Pick the most recently created model using Vertex AI SDK native attribute
    with_times = [(m, getattr(m, 'create_time', None)) for m in models]
    with_times = [x for x in with_times if x[1] is not None]
    if with_times:
        with_times.sort(key=lambda x: x[1], reverse=True)
        return with_times[0][0]
    return models[0] if models else None    